apiVersion: v1
kind: Secret
metadata:
    name: garage-rpc-secret
    namespace: garage
type: Opaque
data:
    rpcSecret: ENC[AES256_GCM,data:DPB+oAk900K0OYwkW91/Xl+nhn1/bJLOwWbF4aiZ8wK3DL+2HgmufyoKAPmk7HYR1KuY1F1cnd+t5Vq1aqmRuCIC6jI8pv8Y0v8O3cz7ZK5EhsDYwxzdFQ==,iv:5GuOBKAQoGp4BX9MI6WJ5MtqlxRrZ9fTX+FgIfizvK4=,tag:GKHVKyIg7O4GyO/Wu4yyzA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDb2J1SUxJMERKdHVnNDQ4
            Wk9yREVEamxOWGI1bzlkM1FqaXZkR3MzZDJVCmRSbWxjY0V4QU5odUZqWm0wVnZC
            VjgycEU0Y3JjMklZWUZKTmJQbWZiNEEKLS0tIEprK3l1bitTNWNhQmdtMlN4QVh5
            azh5TzFZczRNTnpyM3d4VXRFMzFCa2MKtdeYqPPK1T17Cw4WqM5IEtwO/yYzKkmO
            Q9mvvTLcIAoZJeuyQE6zFeKkoxzAR2qME04lo9NsFXI9Z9QTSvJRnw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pszh4rajt03mcmkhgxuyqkyrnu2qe9xgv9g93kymu06z0pzw0feqmrcph8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIejN3RzBTNDVMc0o0blNK
            bVZWb2w0SmxWN3IwL3hNYzVOcUlyMGFNdjNzCmp5a3dNeURCcEdLaDZ3M2NkQkty
            b1BiNmJIczlIcVlBa1Z6Z1AvVnNlZ0EKLS0tIDNvSVhmTEp3WktLaVhWNFdwNUhx
            TGwzRjljMHY0N1RKazZ0dUNTdk12aFUKHLtll7FlYQRnSpREHhTDZiWdZTKzxK45
            L6YctQwzMWEYw8jUHKgm8fJen3L8O5yYMxlJipFYu8xrGGxDwNR/sg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10dmkesu0j4zyr0xqkuvhzzdc2trlp93vlfvcwwfytzj9gefmp4equhleuw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpZVdSSmlTM1RYYnpWWTBK
            TEducWtVU1ljV0s5bUIxaVJ0eCtuVWFFOVQ4CjlSMWhoMi9VSFZ5OUJLT21BZXcy
            dHZTaTZLZFZYVnRVbVhUNlJGeTdZaWsKLS0tIDBaNzA1cnllb0ZHb1pBK3VWdEFG
            R2lpTTBOYUtFa2pHQU82OURsdmhoaGcK9VFjiARpNWtz15g5l6j4N85G7o3H/9v8
            E4W87kLOJjaAz8cmjr7V1jXhsrUHt4eR8tofLhS+nUbTTeJUls3xOA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1f0zkp89kxtfgwm5wrdg0mdhgks93snxprjwkjdzmjr04f5yzqalszr74x7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-03T18:40:12Z"
    mac: ENC[AES256_GCM,data:DpGEXRBrj0L4YuVPCvXkyg6uM2fBSqRSMpjDYi7t2XTKInuCiHfCY+rPq811uAEPyK4PU2JtxiqpcP2IVz3S5ST7jAfQLP2V0kwL0eR9UxfXovoO8qifmUvBHZXJmrfSNIzdgDDBU4J+rRhvoyOBGjoYE75SdOAI8a4HEziyTYE=,iv:5cwghHdWD6smxp3eIOxCBcOymhWQmRsrhc7H7gh+IEc=,tag:XrpO/A/HplyqpgNnV7zbcA==,type:str]
    version: 3.13.2
