apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: garage
  namespace: garage
spec:
  interval: 1h
  chart:
    spec:
      chart: ./script/helm/garage
      sourceRef:
        kind: GitRepository
        name: garage
        namespace: flux-system
      interval: 1h
  valuesFrom:
    - kind: ConfigMap
      name: garage-values
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: StatefulSet
              name: garage
            patch: |
              - op: add
                path: /spec/template/spec/topologySpreadConstraints
                value:
                  - maxSkew: 1
                    topologyKey: kubernetes.io/hostname
                    whenUnsatisfiable: ScheduleAnyway
                    labelSelector:
                      matchLabels:
                        app.kubernetes.io/name: garage
