apiVersion: v1
kind: Secret
metadata:
    name: garage-rpc-secret
    namespace: garage
type: Opaque
data:
    rpcSecret: ENC[AES256_GCM,data:DPB+oAk900K0OYwkW91/Xl+nhn1/bJLOwWbF4aiZ8wK3DL+2HgmufyoKAPmk7HYR1KuY1F1cnd+t5Vq1aqmRuCIC6jI8pv8Y0v8O3cz7ZK5EhsDYwxzdFQ==,iv:5GuOBKAQoGp4BX9MI6WJ5MtqlxRrZ9fTX+FgIfizvK4=,tag:GKHVKyIg7O4GyO/Wu4yyzA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhSHlVZm9oMG1vTzV3U2dt
            N3hCSTZDREwrZ2p6UmwvUktRbm9Ebk9aV2xJCm5iL3VYUzIvU2hwcUx6Rk43dUR4
            M01aSFMzRS9wSzdadkptNU5HVGFBcFkKLS0tIHRGKzV3QXR3TDNicUJuM0R6eXhO
            RElZa1VMSkZFZ0FtRFdIR081WlRWWXcK9DplpMfUyHLYLoQrgWSgYYNTcH/B0UMC
            VgZHZcFfXhBZTOk6jwe+dGEggj26hYayEWbhAGAGspTa2YPzk6kuqg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s27ue93pce8p404tl7ycgfjgmdw7rxglhn8vgyajarv8g54pf5cq6hwzv9
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVYkMrTVpxbGZwd1lDYitx
            NlNCRno3d09ac0VGOGhSYlZCSCtSQU1BRXgwCjUxNC9iNTUwNksrd0J5NXJhWm81
            dyt2ME9NUndMKzBaclhEeEowcWRaV3cKLS0tIDk3ZGErZ2pjU1M0c1BvTXhNN0JY
            VCs0U3JwV0pYR1JvQ04zUUlLaHVZUHMKxtF40P3njjkphXTqLpvH0/yk59+boAHi
            98Z8SmnSHDP1n9SIeHaoLcol7+ClRHqPoQH7Jge78yc/yvdmd41lKg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10dmkesu0j4zyr0xqkuvhzzdc2trlp93vlfvcwwfytzj9gefmp4equhleuw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJOGVmREpSY3hBZSthZCt1
            NjZMcGNFeEJJbFRZSHVIS2dqeU44bVAvOERRCmdFU2xmeit3bFl1SjJNdmFPaWZo
            enhPbXpWaWNQUjNwUmNUNFYyV0tpclUKLS0tIG5GelFiU2dlayttN0hzZ29XRzdP
            Y1NWMUpMK2hsRzV1T3loVmpEZS96YU0KoIL+S2refXHYhDfi8XLO09zejWV4sqUH
            m1VnKBcNQIOwxymTHms8uZQC1gLLvKRzvaD//dC4SLzLS+0aeFXKTA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1f0zkp89kxtfgwm5wrdg0mdhgks93snxprjwkjdzmjr04f5yzqalszr74x7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-03T18:40:12Z"
    mac: ENC[AES256_GCM,data:DpGEXRBrj0L4YuVPCvXkyg6uM2fBSqRSMpjDYi7t2XTKInuCiHfCY+rPq811uAEPyK4PU2JtxiqpcP2IVz3S5ST7jAfQLP2V0kwL0eR9UxfXovoO8qifmUvBHZXJmrfSNIzdgDDBU4J+rRhvoyOBGjoYE75SdOAI8a4HEziyTYE=,iv:5cwghHdWD6smxp3eIOxCBcOymhWQmRsrhc7H7gh+IEc=,tag:XrpO/A/HplyqpgNnV7zbcA==,type:str]
    version: 3.13.2
