apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - garage-secret.yaml
  - helmrepository.yaml
  - poddisruptionbudget.yaml
  - security-headers.yaml
  - ingressroute.yaml
  - garage-helm.yaml
configMapGenerator:
  - name: garage-values
    namespace: garage
    files:
      - values.yaml
    options:
      disableNameSuffixHash: true
