apiVersion: v1
kind: Secret
metadata:
    name: omniroute-secret
    namespace: omniroute
type: Opaque
stringData:
    STORAGE_ENCRYPTION_KEY: ENC[AES256_GCM,data:wnS/EQYh8CPnTHyaq5GpG/D3cPiNqrQ+qqvzjwTpfFO16uKq9yU9TxM/Cp8=,iv:63WWPrfFJnRH5x5Udz017yV2VdKMoqCCEF7itKRzGBI=,tag:8fnahlyNfQiE+nS2nnE0Kg==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:8ShWxle9rZtxlCgaheqQug/iZZptuZcXBTtn965wowyCFvfhjTfGxhgMQoy7unj+juSzZ7iB6hdKGrZoPPPvew==,iv:gXgOKG51sedeeeACkOHcI6qhXZlG8TLwEKGmCemIFgg=,tag:EhZaqPFnxAHwgijaMa9k+w==,type:str]
    API_KEY_SECRET: ENC[AES256_GCM,data:Glff9CqHYAUOV/KOBi2zdL6jvXNTNwVcfYd8zNuEQDwlMLfbY3E4Zsg2Eg3uglwDILO9tY5+voNujXcWdv/blg==,iv:d0SX+l18CWB0h2YI+ON69OXxHP0IY3Be+N2d7cKjokQ=,tag:s0fYz2EFp3ArlUsYFKv+jA==,type:str]
    INITIAL_PASSWORD: ENC[AES256_GCM,data:wHVUvEeFcwAYxEaBLMMQSyUb6bk1TgEDS0XBhJvWNKM=,iv:LXuGNhwCure3dOW9v/iQWuP7jM6mJpaxTod+HPjgA0Q=,tag:NzRqIDN5dAa/uFUmaEgpRg==,type:str]
    OMNIROUTE_WS_BRIDGE_SECRET: ENC[AES256_GCM,data:7ySZb9zjULMWercMTAoTl+VzOWZ2kqM95HnD1qs3JrByFrZ37EWpmURclg==,iv:FkwBmPZglFy55Z3dkFtlVnPZupnYnww/ZtZF7ZndsFQ=,tag:wcF2fatJ8q61emdSYyUhMA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaVFZHU0treTRVSWxnMHVD
            NHdpNU14VEtJM1lZbSszM2NZM01FZ2xscG00ClhUUWc3N01qOVVoT2NvZ1ptZXpj
            dFRTYU9Xb1ArZUV6RlVkWTFMUlhKd0EKLS0tIFBzekY3cFdrckJCOE41MnRVa0w0
            d1FuR0RWZWllUjJQd3FhSXFqbm0veTQKaNu+LB8OgdTbqTwNeqwIisx1fpa0En7k
            FsqUbxiAz3eTsBkF10KQH4oW7WxelFXZ9sQr8DVnxfuS+d05TwajQQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s27ue93pce8p404tl7ycgfjgmdw7rxglhn8vgyajarv8g54pf5cq6hwzv9
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCVnVFZzJBaE5HNjhLMUM2
            M3pLb1FOUE1DbDhYeDNrWjR5T00vQXN4alZzClFxZ1grQXdkQUduSjQwR3VWKzdy
            bTdPREJtcy9IWkZ3L2tnTGZrRlpVVHMKLS0tIDBvS29GNTBVbEV2d1Z5M1VNL0wr
            TXVzU2tpWFNkNzVTSW5xa2FQZ3d1d2cKpeshtHkExCgsdiHW3t3OHTQCZOfYPprs
            FarF/On69tCL6u46eTbMiaHEtfQdBmhmiFhD/ro12uFe+/uPPJwWFg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10dmkesu0j4zyr0xqkuvhzzdc2trlp93vlfvcwwfytzj9gefmp4equhleuw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLb0JYdmpWWVQyeGtUQjhu
            R0pMOG9SYkNXNm9EaXpPWGxVN0JnZElSTENZCnJLRjRlVjBlVlVZSEpJOS94T2or
            NXNWS3J6RVhmNmN6R2VCeG5HQ3o4dDAKLS0tIGRYSWdIRVA0OW9uMVFsRE5BYjJM
            VWhTU3VEZ2VybGNNMDRMcVE3ZWlEY2sKRwPEeasAhR/CFZiK5UB7Qm+C9f12c/ox
            D0kafQWNrS82P0MaYrIELyVw/E2pa6H+IsE7ZkJIcVdq2xDNhA3sNg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1f0zkp89kxtfgwm5wrdg0mdhgks93snxprjwkjdzmjr04f5yzqalszr74x7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-26T10:17:00Z"
    mac: ENC[AES256_GCM,data:bFWaISY1WlZglo7Cgio0CN+t54i+QkXZzM17cL5I93EB+QUkQDlz6PLobq2Zah12R8mP93kDgDGUcHW7o7LYp/zry6DF7UOXG/Zfrh1JcLZoYetCkH3Mq/GFiohpU1to0bEGFYfohHiUonok8GiUvecnz9U2mVO2xt+qzneELZo=,iv:rB/srWXgbhxK75tUd/mSSzyWbWdV5D3WXz5IZ0TdFc4=,tag:uhNTKLddEompSJ6EWHMhiw==,type:str]
    version: 3.13.3
