apiVersion: v1
kind: Service
metadata:
  name: omniroute
  namespace: omniroute
spec:
  type: NodePort
  externalTrafficPolicy: Local
  selector:
    app.kubernetes.io/name: omniroute
  ports:
    - name: dashboard
      port: 20128
      targetPort: dashboard
      nodePort: 32128
    - name: api
      port: 20129
      targetPort: api
      nodePort: 32129
    - name: live-ws
      port: 20132
      targetPort: live-ws
      nodePort: 32132
