apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: litellm-token
  namespace: litellm
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi