apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: litellm-secret
    namespace: litellm
data:
    LITELLM_MASTER_KEY: ENC[AES256_GCM,data:idBP/eOt2muM2ti7Oyz5RghjeG4ZHzQHKAHL50SoNBbrP8aPnFxIkFEOvpjRe35I7HnYA8Ox7EgkbEMP6tL7W+oXf7XRmQ0pUmXk0OV0Bhcp3qw8AwmFzw==,iv:+Ngn9YtI9aMCC21l80kNg++4otZ9ZC9o9pb9K9muUVs=,tag:wD/DMSOXjaCnNqdZ61vZew==,type:str]
    LITELLM_SALT_KEY: ENC[AES256_GCM,data:VL+1XwBINg2mFkOXKM6thvR7ztl/tcn0qK+qPQyl/YSGacPMQN9VhRifXXnNtG2WKAGGgS08HYoDrZKv,iv:uzjJsTQ++XpI11LrRS7dl5cQEKaa6mMx6esuw///oqA=,tag:jicwSBnozwYdD90BUp/75Q==,type:str]
stringData:
    GEMINI_API_KEY: ENC[AES256_GCM,data:W0eyuklRkL0BycQKYZsabxi3GdmKUnHjFeJUehXSMrgasPD+AlZBu07mqd3p+RHAT3EK8gQ=,iv:AWCUnPSZkaY/0IaqwyvBk0u6E67cEAxT6g6IdIcGHlM=,tag:e4dUJMuOaP35n4fHr+wLsQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOajZjbHRkZW0weitBMTBa
            U0dvRTZaUmdoeEM4dlpVN2Y4RCtiWkMrZ3dnCmdsTkZmRko5KzhIUFVkYnpKdlkr
            T3RqYXhKeUN2YTdiR2RUTFA5TUo4NDQKLS0tIG1Fazd3T0ZHcnFuQ3BzR3dPOXov
            MWR2Wit2cXJweldIaHNhdC9Ra0c1YUUKFKdH2ya5zz6mLsmMxXwyqE3rKAyuJOVp
            5ltjqhlyyfgu7Sa2YAT/lOKABS4Bxfst2KztQ2Cv2dVmYk6MdafLtg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s27ue93pce8p404tl7ycgfjgmdw7rxglhn8vgyajarv8g54pf5cq6hwzv9
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwYm9lTE1KTzA3UEVCbSt2
            VnY0cnRQVmZqcWlZY3dNL3hmOHFycHA3TEdjCitzeFY2b3FHZWhRSVVtK0YyQkha
            K205TWNXMEsxN3ZrTHFjc3I5VTFuaUUKLS0tIGFMYzJ3UWtpUjE4NHhhUDVseGpQ
            QUFsVlNaams4a3dVbDhoUGRoWTRoU3MKbB0seKLquWldBe+LnBNYU1A4ubmmcy6k
            Z9jivGXv4HnH8lxjo79+hFWKZfMGqk16vS1lROvuqH6fw5Jp/qO4yg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10dmkesu0j4zyr0xqkuvhzzdc2trlp93vlfvcwwfytzj9gefmp4equhleuw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMUEFPQ2tiWnZwaVZKUHpN
            L3RyQ1VWdVBlakVZa0lSYUxPVHBiY1ZhQzBVCkJ1T3hqdEx1WHRkSXZmM3pUODFE
            TTE1NkYxNDYxb3RVdUZ3NUFjRTZlWGsKLS0tICtYWDhNVklzdEhhckNvYStjR2Qr
            YnBNenN0Q2c4UVhLSDdmTTNGdGwvY1EKvDVHhBeH4YEDoNGK+e1y9k0VT71EIjbj
            p8uhV00xOKn84gt/6fFFmCrEuNm/G+3QzFUK8j1wHk8H/CkasHDtIg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1f0zkp89kxtfgwm5wrdg0mdhgks93snxprjwkjdzmjr04f5yzqalszr74x7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-13T17:17:07Z"
    mac: ENC[AES256_GCM,data:e2dbYyWzbGGfAU8ZGbRVPymUHxwyv1IpyZNPbX+BJbGUXzYM4n+89wpBCyDoKmd+4B1Fp6d1dqGPBUl2aEK9KfDwVME9lC+Zz7zC6XZZbyGSk/E2QiCI+PFX8g7bp0S6oPI+EIb/2DlyNYrQNBa3fC+HugslJ+JWGZXt318jzzw=,iv:zbXaMHUz5bQeWAwdTW5e+3amKoifgvKxjRni51ixjqE=,tag:1rc9/qcrh7Ngj1qaHWTcDQ==,type:str]
    version: 3.13.3
