apiVersion: v1
kind: Service
metadata:
  name: litellm
  namespace: litellm
spec:
  type: NodePort
  externalTrafficPolicy: Local
  selector:
    app: litellm
  ports:
    - name: http
      port: 4000
      targetPort: http
      nodePort: 31400