apiVersion: v1
kind: Secret
metadata:
    name: tunnel-token
    namespace: cloudflared
type: Opaque
stringData:
    #ENC[AES256_GCM,data:FYrQIDmsNUOarakZuQkh12UUpMJOVpiRs9jekoLhPPooeRh6aA6vQ/DJmY1PW2gpL5wjMypjgS1ms8VQiwV4HHguPa6w22iQYw==,iv:HRtshAFhC6OCmYyJeslPWxLuo6U5J38m4jaG3kWOD+s=,tag:R1uH+axDNaWsmAQNuHrhog==,type:comment]
    #ENC[AES256_GCM,data:rcvbHk+kcKx/cUUvy5+njKONspG9H9xdyHsm91hLIAz1kK+RV1B+qJuUJG8W6wQl61f5WjCgYi5CsCL6W6wcRjdl/fA6,iv:X29hs2a7kOZtlI/wSwQ937C8sbjEnWZ6ICK2f34fmLo=,tag:kNp5PDJT8zKQSrw7FUBRsg==,type:comment]
    token: ENC[AES256_GCM,data:88Fzw/W3UzCccOmWcyPrzmLWZhLGnApTYdfSR8vWPAzVtqdNtGz5UTntrb4JVfFckUl1E8blqGkY1bZvjqhOta6P6gYccwQ/kszqi362NJ56eN2dklaqWmdPToXRGIo+EC4V93Fb1ZB5bLa8CgPkNR+llDkVNuIXDBjg/4NKat8k7eMg23nA80xTYg/sAVUnLofjZAtaXCipI6Jzi7HWD4MkHzHaZYQ4WMnfonKF+GxzCP/0qLTT/Q==,iv:5OxbdbGNedQp/4jWzWMK0kQ3ymexXCOBDjR7qeCJdlY=,tag:1eqHeOvfTiubmr+yNVkBkQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBscGFQczd5YUJZcDFoK1Zq
            VkZNTjhJTmhQdGpmQ3hxdmxSczNUK3ZxOFZzClpmUlRQb0c5d3JCenZqSUJlblRn
            M0pKRlY5Mm1qSjVoZko1dmVPbXpLR1kKLS0tIFUreHFGMWpoL0lCTEtaTks3MTVK
            dG9pUDJXdFFGTTFkcHA0aHphelFVNDgKWtVQmOhzMZjKDCYpk2K/t/SXp/SvfTHd
            dssBV99lqVOwVwhLnzle/ND3n/T3sV47AIKtBnsqBuGyfQxRuSr6YQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s27ue93pce8p404tl7ycgfjgmdw7rxglhn8vgyajarv8g54pf5cq6hwzv9
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwMHE1OTZVeGVLMVV5WkhL
            KzNpY2tNZnhaRTlwaEE4L0hMR2xYMHpqd1RFCkNWMW1uZGNEV2dZMkpuWlQ3MW1u
            WURSWmoyNy9EZFQvMVY1TkoxREY4YjgKLS0tIGU5Q09rR0VlV01sM3FsVC83aE9k
            M0YxK0RDRy9Lc0Jocit2UzNGSndlUEUKDIp8tSJ1hReca0jn4uVOGZ3UbxUrp2kM
            mSm7CgtpHMwICbcyZUH2BQrxW9Rif70H3CQ2ZfCQTxNOaNY+RajCsQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10dmkesu0j4zyr0xqkuvhzzdc2trlp93vlfvcwwfytzj9gefmp4equhleuw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlclZ3dm52ckl5T2cyYnJh
            MHJuTzFjN3VGdi84czB1dmk3K0Z5Smp0Q0hRCmdOU0J5SlJxTjN5ZnNST1NLT2Jq
            dVBEZXBHcTA3Si9QbFl0UzJhdDNCazQKLS0tIFcxaER6S0plV2dOblJuZ2hrZlZk
            TG9iUTN3czRCMGlsaGVXY3NpbzR6NXMKyfS3aXNl+y81MS8hLIkQBD/hzOyDg0+b
            LgY8yIYhSyeFlfAPTqYuBKkoil3Pg0kvCX7LZqchCHLKufLxdjS5eQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1f0zkp89kxtfgwm5wrdg0mdhgks93snxprjwkjdzmjr04f5yzqalszr74x7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-05T12:56:59Z"
    mac: ENC[AES256_GCM,data:YXZxYi4REkIALrFdgVZBrQCnle0LaU/0hcNSLM43kyDfcls0BYlQE1CmT5f7QJexShkv+vN56FzjH8MwwomuUR7ymlBVmjFqgEcbmFG8hmQuH1hikZvsb80XfMZukPCaZe12yTmwyt2PEIqBlm77kSINVjjRXEmm96rEgv3rQ8A=,iv:Dl/h7vmGZCmGLUkPo8zLXkpNItZiwS1S/NQd2Bu3Ijs=,tag:MmdMha4vBvkNHjsLphm7vw==,type:str]
    version: 3.13.3
