apiVersion: v1
data:
    DB_DATABASE_NAME: ENC[AES256_GCM,data:7uw4nSPQ/54=,iv:4tSTFBJu0PEFWRTo6oa1NqzaCILXNvLhHEilmYdaITE=,tag:hCqR36CCAboRG9l9fVW5ag==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:X9lzlU2uqd8AqpbPldPZEsR9HqpwL8pBXzPdaFEa2MapE7RqjAafxmmRlSm/xwmvec/wII+MsnTPVtQu808M1D8AYqU7uEj76Yz2z1upVpuoF2fucJMVdQ==,iv:zBH29ZCZho5IPNQvwrZc3vFL0UpgXPwNXMml8LCZMfw=,tag:1k9aJeS9OsScyGJ14WAqJg==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:iayHTaWKeOI=,iv:Hkwnaxhgg7+JvyVb91Z2IMX7MhXflq5gtcUs1jPgREA=,tag:zAwnfcnUBHP2XiNbtCgQ5Q==,type:str]
kind: Secret
metadata:
    name: immich-secret
    namespace: immich
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDMnE2MURiRkJYSkd4NU1E
            dUZFd3lHVHgwMHdQZ2Q5dElRWjBGZWROVGhZClY3bnNIZmZyaDd3d0g2Wk8weTZK
            TE8rQ1NmUkZiTHZsTW5tdkNyblRNVkUKLS0tIDFLV2VVeGw2eUZPWVIzbzJ4TUs5
            QkozdGFoekJzK21hRXZYejB2Nk9hcW8KfZwnBM+YHrTVz9NQrYeukmlNUuhfZ3OX
            sU5PtI9VZDGLzOrwueNKHAi2bYhyhVpofiNR0ik7BZB6gGa8sEpEyQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s27ue93pce8p404tl7ycgfjgmdw7rxglhn8vgyajarv8g54pf5cq6hwzv9
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLN1BnTDdIVHhLLzFVcGhk
            ZGNkQlhYMTErT2Rqb2pxanVrRjhCcG1jYXdFCnN6RCs0Z0xVODlCS1NiS0pVd1g2
            S1ZkanNIZm9OdnFsMXd5R0Y2dmphK2cKLS0tIDd5NVF4cUJvOWNXTlMyOTU5eWVm
            M1lLWUdaNkhETm5wMFV3STJiQzNaZWMKyV5oB31fZNM353nu8FYAp9TYF9ldbunE
            /7vPWp1FxG+4jo5i00lxRhi2PM+W6oK+ZZ9TmmGqSul+GvMVABJB0g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10dmkesu0j4zyr0xqkuvhzzdc2trlp93vlfvcwwfytzj9gefmp4equhleuw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzR2Y4ZU5XcHlJS1lkcVhH
            MDBjTEpnTmhMTzJvZEdxV25iZlptcXcwTVZzCjBZdjFxOE82T0tBS1Y0d0JleDdR
            L3Yxais4Si9xeTMxRXFoZEVlTTZXamcKLS0tIEhiU3E1eGNIWEZqd0FiYkFUQnFQ
            UlZtV2d2WndwS1VRSFY3eXpYUEd6L0UKynx2Z76mJu7S/BylwkQVjSnq1uj27dwO
            p1V/XCPOcHdunhWPWzkRMvtvIUe6dSMk9A+2v2luKRC2cp3vfDfLKw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1f0zkp89kxtfgwm5wrdg0mdhgks93snxprjwkjdzmjr04f5yzqalszr74x7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-02T13:55:41Z"
    mac: ENC[AES256_GCM,data:hEtL9s4kw1xnxZnVeszmmtxBd7eByPmsl4lG6UDdXp5IQfRaM1ZKZNBmuY1H6QfOwnhbG4OBJSd8pEn64vuI4G6TsdxEP+SvaNdqUW0jNnwY6FqGj4glZt2m47EIOuUn1ILn5E5guAZCQ2VWpwmfg5LyRNZQer1qS3JK+yvKzw4=,iv:gn0EOCmJBbldq6i3LOdspB4L5eSi0zkPZ6GBI4v2IpE=,tag:9DbB/arZdZd8/cGW3ndx4A==,type:str]
    version: 3.13.2
