apiVersion: v1
data:
    DB_DATABASE_NAME: ENC[AES256_GCM,data:7uw4nSPQ/54=,iv:4tSTFBJu0PEFWRTo6oa1NqzaCILXNvLhHEilmYdaITE=,tag:hCqR36CCAboRG9l9fVW5ag==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:X9lzlU2uqd8AqpbPldPZEsR9HqpwL8pBXzPdaFEa2MapE7RqjAafxmmRlSm/xwmvec/wII+MsnTPVtQu808M1D8AYqU7uEj76Yz2z1upVpuoF2fucJMVdQ==,iv:zBH29ZCZho5IPNQvwrZc3vFL0UpgXPwNXMml8LCZMfw=,tag:1k9aJeS9OsScyGJ14WAqJg==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:iayHTaWKeOI=,iv:Hkwnaxhgg7+JvyVb91Z2IMX7MhXflq5gtcUs1jPgREA=,tag:zAwnfcnUBHP2XiNbtCgQ5Q==,type:str]
kind: Secret
metadata:
    name: immich-secret
    namespace: immich
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5aDQ4QjhZT3dnQnZESFVO
            cDMvakx4SXg4dkgxUi9vMTd2Q1FkclZrOXh3ClRvUjZTNjZaRHhvZkhWQ1BTMDhV
            bmJwZDhTRFlCZjR3ZlBDeDVjb2dPMFEKLS0tIEtrSkluN044OFBHaFBqVWhGdzE1
            M1d5NUtWY3BjL3NRUWFGWHdJM3BPTGcK2rXzpBL7B1P0N7il2ZAa2JXjBkDIvUZw
            suiwzbucoavucUS/qKrjHf8roKC6w6A5BBW9Oosw6q8v/Uq/KVqv8w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pszh4rajt03mcmkhgxuyqkyrnu2qe9xgv9g93kymu06z0pzw0feqmrcph8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1alJmMmVBdVVKak9lanR0
            TG1zWjBRZ2p6eHI5elYwNjJHRkFrVW85VkJnCjZNS1lsQTdSSzJGbURqVDArdXhY
            Zi9PVXZIWml1Y3Q0RnJUMENicFBGbWcKLS0tIFRYMzZURkhNaUVyRmdQWlpCcDNt
            R082elJoaDVDa1BFQUxWYXhSS2s2c2MKOeVcotXJO2p8LCHSdyRjuNylincUPvx1
            299XLMOtpNwF1ewokEDsrtzbptNgBQIMK3OkYEcUoAGrzbynWQrPIA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10dmkesu0j4zyr0xqkuvhzzdc2trlp93vlfvcwwfytzj9gefmp4equhleuw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwWkZpaG1jVmlINVZBYlVW
            L25ZamhDYWU0Wld1SzNwc2lxYnNGMCtwNW1rClNyd1hVekI5YzA3Wi9XVS9ZTVNH
            RUpaZk1qYjFDYnZDWTR3MW84cGZDUEUKLS0tIDZGZXBuNU5ZQUZOTHVJalRSTUtp
            dURCRFV0bmVVL2ZnYmxkeU9JMVkrckUKmgtmZrA4wyMsDt9FOJ0JX16AYzGH7XLJ
            jarqz0uJOQzu+nUio7zyfm433rJJA73DTmB7BDoF2HXunlitGpUQQw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1f0zkp89kxtfgwm5wrdg0mdhgks93snxprjwkjdzmjr04f5yzqalszr74x7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-02T13:55:41Z"
    mac: ENC[AES256_GCM,data:hEtL9s4kw1xnxZnVeszmmtxBd7eByPmsl4lG6UDdXp5IQfRaM1ZKZNBmuY1H6QfOwnhbG4OBJSd8pEn64vuI4G6TsdxEP+SvaNdqUW0jNnwY6FqGj4glZt2m47EIOuUn1ILn5E5guAZCQ2VWpwmfg5LyRNZQer1qS3JK+yvKzw4=,iv:gn0EOCmJBbldq6i3LOdspB4L5eSi0zkPZ6GBI4v2IpE=,tag:9DbB/arZdZd8/cGW3ndx4A==,type:str]
    version: 3.13.2
