apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: immich
spec:
  interval: 1h
  chart:
    spec:
      chart: immich
      sourceRef:
        kind: HelmRepository
        name: immich
        namespace: flux-system
      interval: 1h
  values:
    controllers:
      main:
        containers:
          main:
            env:
              TZ: Asia/Calcutta
              DB_HOSTNAME: database
              DB_USERNAME: postgres
              DB_DATABASE_NAME: immich
              DB_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: immich-secrets
                    key: DB_PASSWORD

    immich:
      persistence:
        library:
          existingClaim: immich-uploads

    server:
      controllers:
        main:
          containers:
            main:
              image:
                tag: v2.7.5
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: kubernetes.io/hostname
                        operator: In
                        values:
                          - s145

    machine-learning:
      controllers:
        main:
          containers:
            main:
              image:
                tag: v2.7.5
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: kubernetes.io/hostname
                        operator: In
                        values:
                          - s145
      persistence:
        cache:
          enabled: true
          type: emptyDir

    valkey:
      enabled: true
      controllers:
        main:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: kubernetes.io/hostname
                        operator: In
                        values:
                          - s145
      persistence:
        data:
          type: emptyDir
