apiVersion: v1
data:
    DB_DATABASE_NAME: ENC[AES256_GCM,data:us6PJ/bHIcs=,iv:QqdpYClEkRoWUk0j/oHK/s/TsCKlmSp4HoIQYLsi7KY=,tag:E8M7exQwsQ62wMAMGabvJw==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:8llyW0r1q5qus3p5QJFz5Si0rhkiMN1o,iv:x5kYSW+ayadHbwIiKTSRNmes1JDFAiZ+c/HsUgXp/lM=,tag:EkvLbSRwPKZZ7OMWhd6H5w==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:sWcLXRFKR00vmbkw,iv:VX3+pDu9Y9xDZdfe+m5cfX9qvYPalG3WEg5k5ho3EMY=,tag:fko19e1j5iJqliZ7N+aTBQ==,type:str]
kind: Secret
metadata:
    name: immich-secret
    namespace: immich
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBITTg4d1dPVTg5Tis1aGFu
            NVpuN0wvY2hUbEt3NzZjcER5SU9pMWpFb200CmNMN1FuaitQV3J5NHorTlZqcnp2
            dkQ2YVdFd05HTnRzVHRWN1B0T2lvK2cKLS0tIHlxZUt3aXJ2Rll4Z2kybGVEejlX
            SEs3emxwdGx3Q3d6VytsQ0hOODF2YjgKZJknj6sjRPL9bBpXnOUb4QewEWyIsSLK
            GLYSPArki7CpLw2mDFdGk3zziZBdP08k5XJ9+UJTE0g8GhVZBqYclQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s27ue93pce8p404tl7ycgfjgmdw7rxglhn8vgyajarv8g54pf5cq6hwzv9
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1VnRwaDd2UkVQdk9mOUZJ
            SFd4U01RNm5QaGZGZ2xEUnkrZWJBSS9ZaFJBCkRyY3JQVmJheUVnVUFPZ1FVdUtk
            ZFgrdWFrczRaZ1dXSFpuUjVTZGNuU0UKLS0tIDQyaUxxS0QyR0NVNWVSTUE1MkNN
            OFRvZFJtd0FiRXM4Vi9jS0NZMjdaVnMK6v0ZPx1h7cLikRu7d2FBF5zD33bakoWS
            rkCU/vOijcCbbNIJEJkZ8JSgcZ34vaFyIaEjDg7D4d3r2esMa1holA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10dmkesu0j4zyr0xqkuvhzzdc2trlp93vlfvcwwfytzj9gefmp4equhleuw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyR01Zbk5WNlVTSnhKc0c1
            NGE1Rmkyd2xPM255OEhBMVRsdGlDOWNwQVVnCnQrUWg0UFZuaVpVOUVuTm5OL1g1
            MVpuQWZtaUdhNTlrUEkyUVI0aTBES2sKLS0tIGFXUEZLcmdhTURiL3NXTWlpMk1v
            dWk4R3ZxU3o4TkJ2YytXYml6OVVRa1EKpt6RLdDT3VHRMhLWly+4CXCtVMLfIPtr
            6WviDpAJkErY13Azgys76avSRVxjUelX7ciIipiNcCVSWCiBkdNmfw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1f0zkp89kxtfgwm5wrdg0mdhgks93snxprjwkjdzmjr04f5yzqalszr74x7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-20T13:38:44Z"
    mac: ENC[AES256_GCM,data:2Br+v3PTlfIGwoqQayRlfjqSP1D921WreLNO2UKNb5M1VVnzqVF+aftBZEVrO0ynEdIwRHQhC9vP6QnCshkVrZ6CPxLFdtzIZ3zX6bH4SjTIpUr94OsB9cOwfCTu2AJOzjYzK58qMk74fxT15ONWl2yNODI5yVz6O0invU46fKo=,iv:jlbggu259Vln//V8a2WhjDg5k4hXWWsySPHo6TXqcvg=,tag:7mSDnsF7NV071qwUoWd9pg==,type:str]
    version: 3.13.2
