apiVersion: ENC[AES256_GCM,data:bMw=,iv:O6w54mVKbpuOiuONawLV6wbKHZ8fvE6EDUfXhRe3fL4=,tag:SA5Tt4f14Sy2OCkqulA/QQ==,type:str]
kind: ENC[AES256_GCM,data:I4J0DOm+,iv:dPNTy26rLcFU1UzVR/J2NiFhFkPYb5j3lK9zQM5OVnA=,tag:j7XkHOlTEKN2ebbyKtSWzg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:/a80Sejr56xbP5iFGpY=,iv:mICF/ryJMJ9ikGf1BAZcB/ZpuLdUYo7bqTG1y3TfFTY=,tag:eOVNrvLe7N6FgF0hNXIN+w==,type:str]
    namespace: ENC[AES256_GCM,data:2x7XGt8k,iv:GoohOsiC+R/djYjffZU6/IbqII1l4UF2ZGM/iDvFOmw=,tag:hG9jKHyYT/95Xc8Us33feQ==,type:str]
type: ENC[AES256_GCM,data:sUIT2zk9,iv:AwR3WN9XYVgvuGGJxKd1P45U+WSDLnUNtGC7BD7AHUc=,tag:hJJ9daAFKN9EkZ/A4sgbaw==,type:str]
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:eJmnthbLEB4Sr2FSZRFF2NYj1WX8ZRc3ekXDbNK7+oQ=,iv:L6PTGHm6HQchE3GNMJL7J5Y0yDx78U80CHxPjrZflxo=,tag:2BPnaRbpWKY9aBOv4DfQPQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjYnpWOGsxa1dvUU1GU1VF
            bmlPWno4OEw2WVlkTFJEdU1sT0h4K3BxTlhNCkRjZUYvWHF5eU5ldVo0cW9NNzdE
            ajc5RVM5b0QwS294UzNUc0ZKZmhzVzQKLS0tIDJ1bFovNVJIMktyNVBIeEpqbytS
            ZkljSTUyUUFTd0daWmgyTGQ0dGRyMW8KeZ9/MZltIGy7sShZaJWJHYXrAztQpsPO
            wOZsFNg61LS9DmqzUJAUNlia5doV27eoZiMR2p5QxjLdwAOueyNZNg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pszh4rajt03mcmkhgxuyqkyrnu2qe9xgv9g93kymu06z0pzw0feqmrcph8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEalA0Yi9nMzVqdk0zNUI1
            Y0k2RmoyKzJrbm5aK1RsZWl0dXAvejFBSm5rClhoNFRuU0pKRG4xYTBrL0J1aW1E
            SERUWWFHVG12UjhubzBuOGRaNXJpK0kKLS0tIGtaMDVoNDZ1QlZyRUtYc3I3cGlQ
            WC96OTlrOHVibktpUm10bTRJMExEcDgK/UXb/3dbeoOYONa5XREn+MqdKxsKKQSn
            WmTxtvU5ddwkrmxfy8rjmsgteT59+hlEyLW0Wv9SHE7A2TPPjCYyfQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10dmkesu0j4zyr0xqkuvhzzdc2trlp93vlfvcwwfytzj9gefmp4equhleuw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwZUFTdjkreVcrVHgzcDNs
            cVlCK3ViWGtvRXk3dDJGeGtpdXhybC9sSFFvClFzLzh4VHI1UFFGd3VCVDgzc0VN
            b2xMSjZoSExYMDNUazJnQjBnWHhSSVkKLS0tIEhmTjZRK0lreXplY0FMMjg0bC9a
            K0xCUTAzQ21rdElkeDMrc09FcUZLOEEK3cGWIteMEnvQr6aKNN49IHcGvurM4iQc
            nsf8S+Z3RZIN8GemjV9uS6Wc3NoGrZTmQrU6y0mDJD9XI0nmKXwZ5w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16039825yxfmxmgw6xd7ytd7p4zfpfuuv25czrpjsdlhcu3mrvursrxgl30
    lastmodified: "2026-07-02T12:23:37Z"
    mac: ENC[AES256_GCM,data:ADtL1CzGCER4JEvIFMVRs1uSt9thAWFk44L49SNrFS++DHpFmhbh9RkEZlGTdsVrDNjPEC1n5i9v1AxjaUsTxhQCsBvMyEL7evYpQm0JtO4+tatwOlhSv4EADf6POOjUDD5JcRi8OXO3PhH4gYws7cFV4/wSfqQIBGXg1Erz3Ls=,iv:kY9O2nVa/qCE57tbQjnzZf3uRAWb0hiXh5ZUsVZWbe0=,tag:NpvmJ3svM5hOIjRvSKNiWg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
