apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - immich-secret.yaml
  - helmrepository.yaml
  - postgres.yaml
  - valkey.yaml
  - pvc.yaml
  - security-headers.yaml
  - ingressroute.yaml
  - immich-helm.yaml
configMapGenerator:
  - name: immich-values
    namespace: immich
    files:
      - values.yaml
    options:
      disableNameSuffixHash: true
