apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:58I7vw4=,iv:TlwZZi8qBgIgAx6YyEav5JcxJ6U1HHzCYFnpfNSlgDc=,tag:JS35vIVZdH9OKBnAAFhppA==,type:str]
    admin-password: ENC[AES256_GCM,data:wfKs3ykGzyOASGg=,iv:SBMUjtkJy3ayPiL+52Dqnv4Y4LafftmSWANzFE6A9Mk=,tag:Up6mZdPLM4NkTxvNM9a4Yw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArSGtlNDJxcitPOFhuRzNu
            U2M1Z3RYT2E2SGRLVmlJRGZ5dTVBa1F6TUE0ClF4Nmt1aUZnS05zQlBmei90TkVR
            c21xL0EzSW42d0s4YmhSQjBzRVN3amMKLS0tIERnQ1AwcVgxMkt0eWR5VnRNR3lL
            eUxrNjhkTDVrQXpibXVRelpvNUFTQmMKOqw/2BHlpJ9OJzKK7sGvjcarGNxw66Dn
            SkTohJrsW5l2LcXvpGrk+spM7FkyYfbUcBkL34/Y+bgTU5i2eTpXbg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s27ue93pce8p404tl7ycgfjgmdw7rxglhn8vgyajarv8g54pf5cq6hwzv9
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBybjVIVkM2S09vUjcyOUFz
            NnA0ZUFsRDBidDkrb1ZhbnhjQ2h3UXZPazE0CllBSitzQUpMdHU1NEViaGowTkda
            WUJlZ04xK25RRGZodjFQbHprT2I4ZjgKLS0tIHczNjRNS3B4MFpmVXg2Q0Z3NHBw
            eUNrZG54cTN6SlYxS2krQXBDczNXM2sKBPwVyWjoc1853/cJRq68lfNovQ5WFp2L
            3RHpBQI3t+sdW3sr7cSB0p2G/4NlK3zwtA+dyMYqnN7aW7z2Vw9u5A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10dmkesu0j4zyr0xqkuvhzzdc2trlp93vlfvcwwfytzj9gefmp4equhleuw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBObmNNN0IwYnczejQ1dkNz
            eGRUSUo3NHphL1NSK2NaZmVvRzlBKzdNcVdjCkxtdHRKQWM2MzBONk92SEFkNVFD
            MG1vNy9Ma1hmYjA0RUJOamx2M3o5QkUKLS0tIHpPVTkrUVJSckNwMGJ6NW9adXdE
            ZUg5RVFnNFcrOTR2QXNFR204MjZGck0KHf8NomSvO+mRdATosgJgtWOpFreAXdqy
            cFI+0r3VvsSB24JZ66o/m+sgltQANF9n53dOw237QTsJCzmfLQUS/A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1f0zkp89kxtfgwm5wrdg0mdhgks93snxprjwkjdzmjr04f5yzqalszr74x7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-05T14:09:02Z"
    mac: ENC[AES256_GCM,data:3HcwUQViPDvgprnkYZ7DaA8nIh57y+r+dkbGm82cJixOCEHIejdkFMFep5Ftt1pozlYu798XDjRTUJV/e8QZxD3aleNgud5EoNzCcuBsO2O2IfUpgjDcqWbybYdcL26C7Wo4INDLGpRV0BkH1RNeOTetEzhYdCFVyVXQ3dJ+0eg=,iv:nG9iLqKKSc4szSsCiCRlyF/0JB9nKi/P3yHxmVSfRJo=,tag:tDPODeM42ZoiipGTKwawrw==,type:str]
    version: 3.13.3
