apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - grafana-secret.yaml
  - helmrepository.yaml
  - security-headers.yaml
  - ingressroute.yaml
  - monitoring-helm.yaml
configMapGenerator:
  - name: monitoring-values
    namespace: monitoring
    files:
      - values.yaml
    options:
      disableNameSuffixHash: true
